services:
  zoo1:
    image: wurstmeister/zookeeper
    container_name: zoo1
    ports:
      - "2101:2181"
  zoo2:
    image: wurstmeister/zookeeper
    container_name: zoo2
    ports:
      - "2102:2181"
      
  zoo3:
    image: wurstmeister/zookeeper
    container_name: zoo3
    ports:
      - "2103:2181"

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1
    ports:
      - "9001:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_BROKER_ID: 1
    depends_on:
      - zoo1
      - zoo2
      - zoo3

  kafka2:
    image: wurstmeister/kafka
    container_name: kafka2
    ports:
      - "9002:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_BROKER_ID: 2
    depends_on:
      - zoo1
      - zoo2
      - zoo3


  kafka3:
    image: wurstmeister/kafka
    container_name: kafka3
    ports:
      - "9003:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_BROKER_ID: 3
    depends_on:
      - zoo1
      - zoo2
      - zoo3
