services:
    web_server:
        build: 
            context: ./app
        ports:
            - 8080:8080
    nginx:
        restart: always
        build: 
            context: ./nginx
        ports:
            - 80:80
