name: Build and Deploy to AWS EB

on:
 pull_request:
   branches: 
     - master
   types: 
     - closed

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:      
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Create .env file
        uses: ozaytsev86/create-env-file@v1
        with:
            MONGODB_URI: ${{ secrets.MONGODB_PROD_URI }}
            USER_REDIS_PORT: ${{ secrets.USER_REDIS_PORT }}
            JWT_TOKEN_SECRET: ${{ secrets.JWT_TOKEN_SECRET }}
            JWT_TOKEN_EXPIRY: ${{ secrets.JWT_TOKEN_EXPIRY }}
            HASH_SALT_ROUNDS: ${{ secrets.HASH_SALT_ROUNDS }}

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: task-b-env
          environment_name: Taskbenv-env
          version_label: ${{github.sha::8}}
          region: ap-southeast-1
          deployment_package: deploy.zip